name: Lint Markdown

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          fix: true
          config: |
            .markdownlint-cli2.jsonc
          globs: |
            **/*.md
            !node_modules
